// Authentication

//Register
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';

//Activations
export const ACTIVATION_SUCCESS = 'ACTIVATION_SUCCESS';
export const ACTIVATION_FAIL = 'ACTIVATION_FAIL';
export const SET_AUTH_LOADING = 'SET_AUTH_LOADING';
export const REMOVE_AUTH_LOADING = 'REMOVE_AUTH_LOADING';

//login
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const USER_LOADED_SUCCESS = 'USER_LOADED_SUCCESS';
export const USER_LOADED_FAIL = 'USER_LOADED_FAIL';


//autentication / refresh
export const AUTHENTICATED_SUCCESS = 'AUTHENTICATED_SUCCESS';
export const AUTHENTICATED_FAIL = 'AUTHENTICATED_FAIL';
export const REFRESH_SUCCESS = 'REFRESH_SUCCESS';
export const REFRESH_FAIL = 'REFRESH_FAIL';

//logout
export const LOGOUT = 'LOGOUT';



//password reset
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL';
export const RESET_PASSWORD_CONFIRM_SUCCESS = 'RESET_PASSWORD_CONFIRM_SUCCESS';
export const RESET_PASSWORD_CONFIRM_FAIL = 'RESET_PASSWORD_CONFIRM_FAIL';


// Alerts
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

//-----------------------------------------------------------------------------

// Explore
//
export const GET_EXPLORE_SUCCESS = 'GET_EXPLORE_SUCCESS';
export const GET_EXPLORE_FAIL = 'GET_EXPLORE_FAIL';


//-----------------------------------------------------------------------------

// Business Actions
export const REGISTER_BUSINESS_REQUEST = 'REGISTER_BUSINESS_REQUEST';
export const REGISTER_BUSINESS_SUCCESS = 'REGISTER_BUSINESS_SUCCESS';
export const REGISTER_BUSINESS_FAIL = 'REGISTER_BUSINESS_FAIL';

//-----------------------------------------------------------------------------

// Loading
export const SET_LOADING = "SET_LOADING";





// Categories
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_FAIL = 'GET_CATEGORIES_FAIL';

// Articles
export const GET_ARTICLES_LIST_SUCCESS = 'GET_ARTICLES_LIST_SUCCESS';
export const GET_ARTICLES_LIST_FAIL = 'GET_ARTICLES_LIST_FAIL';
export const GET_ARTICLES_LIST_CATEGORIES_SUCCESS = 'GET_ARTICLES_LIST_CATEGORIES_SUCCESS';
export const GET_ARTICLES_LIST_CATEGORIES_FAIL = 'GET_ARTICLES_LIST_CATEGORIES_FAIL';
export const GET_ARTICLES_SUCCESS = 'GET_ARTICLES_SUCCESS';
export const GET_ARTICLES_FAIL = 'GET_ARTICLES_FAIL';

export const GET_ARTICLES_PAGINATION_RESULTS_SUCCESS = 'GET_ARTICLES_PAGINATION_RESULTS_SUCCESS';
export const GET_ARTICLES_PAGINATION_RESULTS_FAIL = 'GET_ARTICLES_PAGINATION_RESULTS_FAIL';

export const GET_SEARCH_ARTICLES_SUCCESS = 'GET_SEARCH_ARTICLES_SUCCESS';
export const GET_SEARCH_ARTICLES_FAIL = 'GET_SEARCH_ARTICLES_FAIL';