// Business Actions
export const GET_REGISTER_BUSINESS_SUCCESS = 'GET_REGISTER_BUSINESS_SUCCESS';
export const GET_REGISTER_BUSINESS_FAIL = 'GET_REGISTER_BUSINESS_FAIL';


export const GET_REGISTER_BUSINESS_LIST_SUCCESS = 'GET_REGISTER_BUSINESS_LIST_SUCCESS';
export const GET_REGISTER_BUSINESS_LIST_FAIL = 'GET_REGISTER_BUSINESS_LIST_FAIL';