# Generated by Django 3.2.16 on 2023-10-25 01:41

import apps.dish.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register_business', '0001_initial'),
        ('category', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('images', models.ImageField(blank=True, help_text='Imagen representativa del plato', max_length=500, null=True, upload_to=apps.dish.models.dish_thumbnail_directory)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register_business.registerbusiness')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.category')),
            ],
        ),
    ]
