# Generated by Django 3.2.16 on 2023-10-16 01:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterBusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('open_days', models.CharField(max_length=7)),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('location', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('images', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/')),
                ('verified', models.BooleanField(default=False)),
                ('registration_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
