# Generated by Django 3.2.16 on 2023-10-21 00:45

import apps.register_business.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_business', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerbusiness',
            name='images',
            field=models.ImageField(blank=True, help_text='Foto principal del negocio', max_length=500, null=True, upload_to=apps.register_business.models.blog_thumbnail_directory),
        ),
    ]
