# Generated by Django 3.2.16 on 2023-10-16 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_business', '0002_registerbusiness_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerbusiness',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='registerbusiness',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='registerbusiness',
            name='open_days',
            field=models.CharField(max_length=15),
        ),
    ]
